### ISSUE TITLE
MobaXterm : not registry key 'M'

### ISSUE THREAD

**Issue by cpainchaud** [XMCyber/XMCredentialsDecryptor#4]
Hi,

 thank you for sharing this, I am using MobaXterm 23.0 and your script seems to be running fine until this:

`Traceback (most recent call last):
  File "Z:\vault\tools\XMCredentialsDecryptor\Tools\mobaxterm.py", line 129, in run
    Key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, 'Software\Mobatek\\MobaXterm\\M')
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\vault\tools\XMCredentialsDecryptor\main.py", line 14, in <module>
    mobaxterm.run()
  File "Z:\vault\tools\XMCredentialsDecryptor\Tools\mobaxterm.py", line 144, in run
    Value.encode('ansi')
UnboundLocalError: local variable 'Value' referenced before assignment
`

**Comment by cpainchaud** [comment]
![image](https://user-images.githubusercontent.com/6696638/220931826-5ff9e1cc-7cf1-4776-bd23-8ecf69190412.png)

**Comment by cpainchaud** [comment]
as you can see there is no 'M' entry.
I have a Master password setup

**Comment by the-Arioch** [comment]
check [Misc] section of MobaXterm.ini file

**Comment by komodikkio** [comment]
> check [Misc] section of MobaXterm.ini file

Sorry for resurrecting this issue but I have the same error, how could i solve this?
What should i look for in the ini file, and what to do after i find this value?

I didn't had the M reg key, so i created it and added this REG_SZ: 
myusername@computername
with the value i found in Sesspass section of the .mobaconf file

The script now does not gives error anymore, but it doesn't export password as well

Then i tried editing the mobaxterm.py's 131th row to
 Value, ValueType = winreg.QueryValueEx(Key, 'myactualuser@myactualcomputername')
this way there's no error but credentials are not exported 

To add some info, the mobaxterm settings and sessione were imported on this device from a previous device, so i tried as well to use the oldusername@oldcomputername,  but this throws the error again

Thanks a lot

**Comment by srocdocs** [comment]
My solution in mobaxterm.py Add lines after line 140:
 except FileNotFoundError:
                Value=""
                masterPasswordUse = 0

**Comment by komodikkio** [comment]
Hi srodocs,
made this edit on mobaxterm.py:

```
            except FileNotFoundError:
                Value=""
                masterPasswordUse = 0
                cipher = MobaXtermCrypto(
                    platform.node().encode('ansi'),
                    os.getlogin().encode('ansi'),
                    Value.encode('ansi')
                )
```
But when i start the main.py i get this:
```
python .\main.py
----Running WinSCP Password Decryptor----
----Running RoboMongo Password Decryptor----
----Running MobaXTerm Password Decryptor----
```
Thanks anyway for taking the time to reply :)

**Comment by srocdocs** [comment]
So no error but also no output of passwords? Have you checked in the registry that the passwords are there? If they are then I don't know why the code would not work.

**Comment by komodikkio** [comment]
I forgotten i moved the credentials back to the file
Now i moved them back to the registry and i'm trying again, but it stucks here:
```
 python .\main.py
----Running WinSCP Password Decryptor----
----Running RoboMongo Password Decryptor----
----Running MobaXTerm Password Decryptor----

------------------Credentials-------------------
```
A bit further anyway.
I will retry after a complete logout or a reboot, as soon as i can cause i'm @work actually
Thanks again

EDIT: even after rebooting, keeps getting stuck at 
```
------------------Credentials-------------------
```

**Comment by vlarocco** [comment]
I had a similar issue and I was able to resolve it. 

Here's what I found.

1) At first I did not have the registry entry under "Software\\Mobatek\\MobaXterm\\M". I resolved this by rebooting my computer and I could see the entry.

2) After that I still had the try failing at  
`Value,` ValueType = winreg.QueryValueEx(Key, os.getlogin() + '@' + platform.node())`
I looked at the values (Key, os.getlogin() + '@' + platform.node()) and I noticed that they did not match the registry key name and that's why it wasn't returning a value. 

3) I created variable called loginKey and set it to the name in the registry. 
`loginKey = "{myValue}"`

<img width="806" height="112" alt="Image" src="https://github.com/user-attachments/assets/1a84069b-bf67-466c-b2f5-40f24c54fed0" />

4) I then updated the Value to set to the following: 
```
Value, ValueType = winreg.QueryValueEx(Key,loginKey)
# Value, ValueType = winreg.QueryValueEx(Key, os.getlogin() + '@' + platform.node())
```
There's probably a cleaner way to actually resolve this, but I just needed this for a quick lookup and I didn't have time to write an update to the script to fully resolve the error.

**Comment by komodikkio** [comment]
Hi @vlarocco thanks for the details
from a backup, i imported only the sessions on a new machine and noticed that now there's the M key
Now I have the same error you're referring to, but can't figure out to what i should set the variable 
loginKey = "{myValue}"

Thanks again

**Comment by vlarocco** [comment]
Hi @komodikkio 

You want to set the {myvalue} equal to the name of master password hash in your registry 

Computer\HKEY_CURRENT_USER\Software\Mobatek\MobaXterm\M

<img width="806" height="112" alt="Image" src="https://github.com/user-attachments/assets/46f35871-7ae2-419a-8d58-9371fea8b021" />

**Comment by komodikkio** [comment]
Hi @vlarocco, thanks a lot for making it clear for me
I will try ASAP and I'll let you know
Thanka

**Comment by komodikkio** [comment]
Hi @vlarocco , i tryed the approach you suggested, but something isn't working yet

I defined at the top of the file mobaxterm.py my variable: 
```
#!/usr/bin/env python3
import sys, os, platform, random, base64, itertools, winreg
from Crypto.Cipher import AES
from DPAPI import *
from base64 import *

loginKey = 'myusername@mydomain.tld'
```
and edited the line (~131) using loginkey:
```
# Value, ValueType = winreg.QueryValueEx(Key, os.getlogin() + '@' + platform.node())
Value, ValueType = winreg.QueryValueEx(Key,loginKey)
```
but i still got this error:

```
 python.exe .\main.py
----Running WinSCP Password Decryptor----
----Running RoboMongo Password Decryptor----
----Running MobaXTerm Password Decryptor----

---------------MasterPasswordHash---------------
b'14chars/alonghash=='

------------------Credentials-------------------
Traceback (most recent call last):
  File "XMCredentialsDecryptor-master\main.py", line 14, in <module>
    mobaxterm.run()
    ~~~~~~~~~~~~~^^
  File "XMCredentialsDecryptor-master\Tools\mobaxterm.py", line 157, in run
    CredentialPassword = cipher.DecryptCredential(
                         ~~~~~~~~~~~~~~~~~~~~~~~~^
        CredentialPassword
        ^^^^^^^^^^^^^^^^^^
    ).decode('ansi')
    ^
  File "XMCredentialsDecryptor-master\Tools\mobaxterm.py", line 110, in DecryptCredential
    return self.DecryptPassword(Ciphertext)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "XMCredentialsDecryptor-master\Tools\mobaxterm.py", line 107, in DecryptPassword
    return cipher.decrypt(base64.b64decode(Ciphertext))
                          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "mypath\AppData\Local\Programs\Python\Python314\Lib\base64.py", line 85, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Invalid base64-encoded string: number of data characters (41) cannot be 1 more than a multiple of 4
```

I noticed that the value displayed for "alonghash==" in the output of the script it's different from what i can see in the registry as the value of the loginkey. Is that normal?

Thanks a lot for any input you could give me

Cheers

**Comment by vlarocco** [comment]
@komodikkio Sorry I missed this update from you. 

The output from MasterPasswordHash will be different because it's displaying the decrypted value. 

The error you having is something I'm not experiencing in a different section.

<img width="717" height="375" alt="Image" src="https://github.com/user-attachments/assets/5ee09195-ac9b-4167-b150-f98a3167c07d" />

I don't have that registry entry and so when I run the script it skips that section with the "except FileNotFoundError:"

Options you would have is figure out why that's getting an incorrect value or comment out that section if you just need the passwords. 

-Victor
